runtime: nodejs16
env: standard
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

# make sure to include code below
beta_settings:
    cloud_sql_instances: ez-marketing-bck:us-south1:alberto-turcios